### ISSUE TITLE
Remove -XX:MaxPermSize=512m in the example

### ISSUE THREAD

**Issue by yyamano** [mulesoft/docs-munit#153]
https://github.com/mulesoft/docs-munit/blob/v2.3/modules/ROOT/pages/munit-maven-plugin.adoc#additional-argument-lines

```
<argLine>-XX:MaxPermSize=512m</argLine>
```

MaxPermSize option is removed in Java 8. With the option,  I get a warning message "OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=2560m; support was removed in 8.0".

Could you remove it to avoid confusion?

See https://www.oracle.com/java/technologies/javase/8-compatibility-guide.html for the change in Java 8.

```
The command line flags PermSize and MaxPermSize have been removed and are ignored. If used on the command line a warning will be emitted for each.

Java HotSpot(TM) Server VM warning: ignoring option PermSize=32m; support 
was removed in 8.0
Java HotSpot(TM) Server VM warning: ignoring option MaxPermSize=128m; support 
was removed in 8.0
```

**Comment by Crispy-Salesforce** [comment]
@yyamano, we are closing this contribution because it has exceeded the age limit for a timely merge.
If the contribution is still valid, please, open a separate GitHub issue or pull request.
Thanks!
