### ISSUE TITLE
MUnit Maven Plugin - what would be syntax to -Dcoverage ?

### ISSUE THREAD

**Issue by john-ekka** [mulesoft/docs-munit#159]

**Comment by john-ekka** [comment]
attached text file has the command which i tried
[command tried.txt](https://github.com/mulesoft/docs-munit/files/6224692/command.tried.txt)

**Comment by Crispy-Salesforce** [comment]
@john-ekka, we are closing this contribution because it has exceeded the age limit for a timely merge. 
If the contribution is still valid, please, open a separate GitHub issue or pull request.
Thanks!
