### ISSUE TITLE
Why call code 'production code'

### ISSUE THREAD

**Issue by AndrewHumphriesNo1** [mulesoft/docs-munit#230]
"The Assert That event processor allows you to run assertions to validate the state of a Mule event’s content. You can use the Assert That processor to validate the Mule event after the production code runs." 

From here https://docs.mulesoft.com/munit/latest/assertion-event-processor

Not sure why these docs refer to 'production' code.  You are actually referring to the running code / flow in a mule application,  it doesn't have to be in a production environment.

**Comment by Crispy-Salesforce** [comment]
@AndrewHumphriesNo1, we are closing this contribution because it has exceeded the age limit for a timely merge.
If the contribution is still valid, please, open a separate GitHub issue or pull request.
Thanks!
